# Run separately: julia --project=test test/simulation_diagnostics.jl
using Test, Random, Statistics, Distributions
include(joinpath(@__DIR__, "support", "simulation_diagnostics.jl"))
using .SimulationDiagnostics

# Simple integer generator makes the external fixtures independent of either
# Julia's or R's random-number implementation.
function diagnostic_reference_draws()
    draws = zeros(1024, 4)
    for chain in axes(draws, 2)
        state = chain + 127
        for t in axes(draws, 1)
            state = mod(16807 * state, 2147483647)
            innovation = state / 2147483647 - 0.5
            draws[t, chain] = innovation + (t > 1 ? 0.8 * draws[t - 1, chain] : 0.0)
        end
    end
    return draws
end

@testset "Diagnostics against Stan posterior 1.6.1" begin
    # References generated by R's independently maintained posterior package.
    # Reproduce the input with the loop above translated to R, then evaluate:
    # c(posterior::rhat(x), posterior::ess_bulk(x), posterior::ess_tail(x),
    #   posterior::mcse_mean(x))
    draws = diagnostic_reference_draws()
    cases = (
        (draws, (1.01060273059942185, 471.12245895574455,
                 785.48143008782188, 0.022658965117361398)),
        (round.(8 .* draws) ./ 8, (1.0101169458595205, 472.72810999715227,
                                  788.83684205897441, 0.022722493986956208)),
        (draws .+ [-1 0 0 1], (1.76541769848067043, 6.10005826180703625,
                              33.771454827439655, 0.34582489006216072)),
        (draws .* [1 1 4 4], (1.26673327225333821, 434.58323710652519,
                             181.55323645876354, 0.074798835380141621)),
        (exp.(3 .* draws), (1.01060273059942185, 471.12245895574455,
                           785.48143008782188, 0.27018413312475581)),
    )
    for (input, reference) in cases
        result = chain_diagnostics(input)
        for (actual, expected) in zip(result, reference)
            @test actual ≈ expected rtol=1e-11
        end
    end

    # A nonlinear transformation preserves bulk ranks, but a mean's error must
    # use the original values. Substituting rank ESS here gives a wrong answer.
    skewed = exp.(3 .* draws)
    result = chain_diagnostics(skewed)
    @test result.bulk_ess ≈ chain_diagnostics(draws).bulk_ess
    @test !isapprox(result.mcse_mean, std(skewed) / sqrt(result.bulk_ess); rtol=0.05)
end

# Direct small-sample formula, independent of the diagnostic library's helpers.
function hand_rank_rhat(draws)
    ranks = map(draws) do value
        count(<(value), draws) + (count(==(value), draws) + 1) / 2
    end
    scores = quantile.(Normal(), (ranks .- 3 / 8) ./ (length(draws) + 1 / 4))
    n = size(scores, 1) ÷ 2
    split = hcat(scores[1:n, :], scores[end - n + 1:end, :])
    within = mean(var.(eachcol(split)))
    between = n * var(mean.(eachcol(split)))
    return sqrt(((n - 1) * within + between) / (n * within))
end

@testset "Rank and folded split R-hat formula" begin
    draws = reshape(Float64.(mod.((1:80) .^ 2, 37)), 20, 4)
    folded = abs.(draws .- median(draws))
    expected = max(hand_rank_rhat(draws), hand_rank_rhat(folded))
    @test chain_diagnostics(draws).rhat ≈ expected rtol=1e-13
    @test chain_diagnostics(draws).rhat ≈ chain_diagnostics(-3 .* draws .+ 7).rhat
end

function stationary_ar_draws(rng, n, chains, coefficient)
    draws = randn(rng, n, chains)
    innovation_scale = sqrt(1 - coefficient^2)
    for chain in 1:chains, t in 2:n
        draws[t, chain] = coefficient * draws[t - 1, chain] +
                         innovation_scale * draws[t, chain]
    end
    return draws
end

@testset "Independent and autocorrelated chains" begin
    rng = MersenneTwister(20260928)
    n, chains = 6000, 4
    total = n * chains
    independent = chain_diagnostics(randn(rng, n, chains))
    @test independent.rhat < 1.01
    @test 0.8 * total < independent.bulk_ess < 1.2 * total
    @test 0.8 * total < independent.tail_ess < 1.2 * total
    @test independent.mcse_mean ≈ 1 / sqrt(total) rtol=0.1

    for coefficient in (0.8, -0.5)
        draws = stationary_ar_draws(rng, n, chains, coefficient)
        result = chain_diagnostics(draws)
        expected_ess = total * (1 - coefficient) / (1 + coefficient)
        @test result.rhat < 1.01
        @test result.bulk_ess ≈ expected_ess rtol=0.25
        @test result.mcse_mean ≈ 1 / sqrt(expected_ess) rtol=0.15
        @test 0 < result.tail_ess
    end
end

@testset "Failed mixing and undefined diagnostics" begin
    rng = MersenneTwister(62)
    draws = randn(rng, 1200, 4)
    shifted = chain_diagnostics(draws .+ [-3 -1 1 3])
    @test shifted.rhat > 1.5
    @test shifted.bulk_ess < 30
    @test shifted.tail_ess < 200

    # Equal means with very different spreads need folded R-hat.
    scaled = chain_diagnostics(draws .* [0.1 0.1 3 3])
    @test scaled.rhat > 1.3

    # Splitting detects within-chain drift even when all chain means agree.
    drift = draws .+ vcat(fill(-3.0, 600), fill(3.0, 600))
    @test chain_diagnostics(drift).rhat > 1.3

    for constant in (zeros(100, 4), repeat([1.0 2 3 4], 100),
                     hcat(zeros(1200), draws[:, 2:end]))
        @test all(isnan, chain_diagnostics(constant))
    end
    @test_throws ArgumentError chain_diagnostics(zeros(9, 4))
    @test_throws ArgumentError chain_diagnostics(zeros(100, 1))
    @test_throws ArgumentError chain_diagnostics(fill(NaN, 100, 4))
    @test_throws ArgumentError chain_diagnostics(fill(Inf, 100, 4))
    @test all(isfinite, chain_diagnostics(draws[1:1199, :]))
    @test all(isfinite, chain_diagnostics(draws[1:10, :]))
end
