"""Generate independent Julia fixtures using statsmodels, NumPy, and SciPy.

Run in a separate environment with requirements.txt installed. This script never
loads DynamicFactorModeling or reproduces its filtering/smoothing recursions.
The Julia user compares its output against these external implementations.
"""

import argparse
from pathlib import Path

import numpy as np
import scipy
from scipy.linalg import solve_discrete_lyapunov
import statsmodels
from statsmodels.tsa.statespace.kalman_smoother import KalmanSmoother


def julia_array(values):
    values = np.asarray(values)
    # Julia reshape and NumPy's Fortran order both put the first index first.
    entries = ["missing" if np.isnan(x) else repr(float(x)) for x in values.ravel(order="F")]
    datatype = "Union{Missing,Float64}" if np.isnan(values).any() else "Float64"
    dimensions = ", ".join(str(n) for n in values.shape)
    return f"reshape({datatype}[{', '.join(entries)}], {dimensions})"


def fixture(rng, index):
    states = index % 5 + 1
    series = (index // 5) % 4 + 1
    times = index % 11 + 1
    transition = rng.normal(size=(states, states))
    transition *= (0.15 + 0.8 * rng.random()) / max(abs(np.linalg.eigvals(transition)))
    design = rng.normal(size=(series, states))
    process_root = rng.normal(size=(states, states))
    observation_root = rng.normal(size=(series, series))
    process_cov = process_root @ process_root.T + 0.2 * np.eye(states)
    observation_cov = observation_root @ observation_root.T + 0.3 * np.eye(series)
    intercept = rng.normal(size=states)
    initial_root = rng.normal(size=(states, states))
    initial_cov = initial_root @ initial_root.T + 0.4 * np.eye(states)
    initial_mean = rng.normal(size=states)
    regressors = 1 + index % 2
    exogenous = rng.normal(size=(times, regressors))
    coefficients = rng.normal(size=(series, regressors))
    offsets = exogenous @ coefficients.T
    data = rng.normal(size=(times, series)) + offsets
    # Every fourth case is complete; others include partial and whole missing rows.
    if index % 4:
        data[rng.random(data.shape) < 0.3] = np.nan
        data[index % times, :] = np.nan

    external = KalmanSmoother(k_endog=series, k_states=states, k_posdef=states)
    external.bind(np.ascontiguousarray(data))
    external.design = design
    external.transition = transition
    external.selection = np.eye(states)
    external.obs_cov = observation_cov
    external.state_cov = process_cov
    external.state_intercept = intercept
    external.obs_intercept = offsets.T
    # statsmodels initializes x_1 | no observations; this package initializes x_0.
    external.initialize_known(intercept + transition @ initial_mean,
                              transition @ initial_cov @ transition.T + process_cov)
    external.tolerance = 0.0  # Disable its steady-state shortcut.
    result = external.smooth()
    # Forecasts in missing rows are still the complete fitted conditional mean.
    predicted_y = result.predicted_state[:, :-1].T @ design.T + offsets
    stationary_cov = solve_discrete_lyapunov(transition, process_cov)

    values = {
        "H": design, "A": coefficients, "F": transition, "μ": intercept,
        "R": observation_cov, "Q": process_cov, "Z": np.eye(regressors),
        "y": data, "z": exogenous, "initial_mean": initial_mean,
        "initial_cov": initial_cov, "predicted_y": predicted_y,
        "filtered": result.filtered_state.T,
        "predicted_cov": result.predicted_state_cov[:, :, :-1],
        "filtered_cov": result.filtered_state_cov,
        "smoothed": result.smoothed_state.T,
        "smoothed_cov": result.smoothed_state_cov,
        "stationary_cov": stationary_cov,
    }
    return "(\n" + "".join(f"    {name} = {julia_array(value)},\n" for name, value in values.items()) + "),\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path(__file__).with_name("statsmodels_fixtures.jl"))
    parser.add_argument("--cases", type=int, default=20)
    parser.add_argument("--seed", type=int, default=9272026)
    args = parser.parse_args()
    rng = np.random.default_rng(args.seed)
    header = (f"# Generated by generate_statsmodels.py; seed={args.seed}, cases={args.cases}.\n"
              f"# statsmodels {statsmodels.__version__}, NumPy {np.__version__}, SciPy {scipy.__version__}.\n"
              "# Regenerate rather than edit the numeric reference values.\n[\n")
    args.output.write_text(header + "".join(fixture(rng, i) for i in range(args.cases)) + "]\n")
    print(f"Wrote {args.cases} independent reference cases to {args.output}")


if __name__ == "__main__":
    main()
